### ISSUE TITLE
[1.2] Support Laravel 10

### ISSUE THREAD

**Issue by TFSThiagoBR98** [Laragear/TwoFactor#40]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [x] I issued a PR with the implementation: #41 

### Description

Since Laravel 10 was released.

### Code sample

```php
N/A
```

**Comment by DarkGhostHunter** [comment]
Hands full under contract. PR are welcome. Italo Baeza C.El 14-02-2023, a la(s) 20:06, Thiago França da Silva ***@***.***> escribió:﻿
Please check these requirements

 This feature helps everyone using this package
 It's feasible and maintainable
 It's non breaking
 I issued a PR with the implementation (optional)

Description
Since Laravel 10 was released.
Code sample
N/A

**Comment by TFSThiagoBR98** [comment]
@DarkGhostHunter No problem, I sent a PR, when you have some time you can please review it.
