### ISSUE TITLE
Issuer missing or double

### ISSUE THREAD

**Issue by Weemple** [Laragear/TwoFactor#48]
### PHP & Platform

8.2.4

### Laravel version

10.13.5

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

**Expected result**
otpauth://totp/Laravel:taylor@laravel.com?secret=THISISMYSECRETPLEASEDONOTSHAREIT&issuer=Laravel&label=taylor%40laravel.com&algorithm=SHA1&digits=6&period=30

### Description

**Result without setting the issuer config variable**
otpauth://totp/%3A:taylor@laravel.com?label=%3Ataylor%40laravel.com&secret=THISISMYSECRETPLEASEDONOTSHAREIT&algorithm=SHA1&digits=6

**Result with setting the issuer config variable**
otpauth://totp/Name%3AName:taylor@laravel.com?issuer=Name&label=Name%3Ataylor%40laravel.com&secret=THISISMYSECRETPLEASEDONOTSHAREIT&algorithm=SHA1&digits=6

### Reproduction

```php
$secret = $user->createTwoFactorAuth();
```

**Comment by DarkGhostHunter** [comment]
What's the problem?

By default, the OTP Auth URL [uses the application name](https://github.com/Laragear/TwoFactor/blob/676e794834ed7f562e2718999feb0d93244c070f/src/Models/Concerns/SerializesSharedSecret.php#L27) as issuer when not present (`null`), `Laravel` by default.

In any case, I'm pushing a patch for #51 to throw _something_ if the issuer is empty.

**Comment by Weemple** [comment]
The issue is that currently don’t work. It use %3A instead of “Laravel”. And if I set a name, then the name is used two times

**Comment by DarkGhostHunter** [comment]
> The issue is that currently don’t work. It use %3A instead of “Laravel”. And if I set a name, then the name is used two times

Can you dump the following?

- `config('app.name')`
- `config('two-factor.issuer')`

Again, the patch version is live and you should get an error if you set an empty issuer. When it's empty, it uses the application name. It's replicated at the `issuer` query because the first is to set the [app + account name], like `Laravel:taylor@laravel.com`.

I don't know why you're not returning the issuer, but there must be a problem on your `two-factor.php` config file.

**Comment by Weemple** [comment]
Here two detailed example of the issue.

.env
`APP_NAME=AppName`

two-factor.php
`'issuer' => env('OTP_TOTP_ISSUER'),`

`\Log::info(config('app.name'));`
AppName

`\Log::info(config('two-factor.issuer'));`
AppName

**Missing name issue**
![google2](https://github.com/Laragear/TwoFactor/assets/43726381/e7a1ae51-edfa-4a5d-846d-0058351aeb22)

![microsoft2](https://github.com/Laragear/TwoFactor/assets/43726381/3f548601-ba06-47d6-bf3a-5632e61d8694)

--------

.env
`APP_NAME=AppName`

two-factor.php
`'issuer' => env('APP_NAME'),`

`\Log::info(config('app.name'));`
AppName

`\Log::info(config('two-factor.issuer'));`
AppName

**Double name issue**
![google](https://github.com/Laragear/TwoFactor/assets/43726381/2cb2216b-d359-43b5-9eaf-8ce3cfa8515b)

![microsoft](https://github.com/Laragear/TwoFactor/assets/43726381/2db69808-c812-464d-83dc-e7755510152a)

**Comment by DarkGhostHunter** [comment]
Are you on v1.2.2?

**Comment by Weemple** [comment]
v1.2.1

**Comment by DarkGhostHunter** [comment]
> v1.2.1

Try v1.2.2

**Comment by helios-sr** [comment]
Hi Italo,

Thanks for implementing this library. Really helped in getting 2FA sorted in my project.

I've looked at your library and detected the lines that cause this non or double issuer. I've managed to mitigate the bug on my project by modifying the output of the toUri() function. I've tried to do a PR but I'm not used to gitHub and run out of time, so I'll post a possible solution here in hopes you'll consider it.

The first suggestion I have is to add the app name fallback in the 'label' so it doesn't hit the DB as ':foo@bar' when no label nor issuer is found on the config:

<img width="823" alt="image" src="https://github.com/Laragear/TwoFactor/assets/146040315/3e658889-3d85-4bb6-a595-e9d3a3a3ca8a">
TwoFactorAuthentication.php line 111

Original:
`$issuer = config('two-factor.label') ?? config('two-factor.issuer');`

New:
`$issuer = config('two-factor.label') ?? config('two-factor.issuer') ?? config('app.name');`


The second and most important is to fix the toUri function of the SerializesSharedSecret trait
This is the original code:
<img width="810" alt="image" src="https://github.com/Laragear/TwoFactor/assets/146040315/c171d06d-385a-4f4e-bf93-2a9c17f9beda">

Because the label already contains the issuer when present '<the_issuer>:<account_name>', line 39 adds it twice:
'<the_issuer>%3A<the_issuer>:<account_name>?...'
Or if you don't have issuer then you get '%3A:<account_name>?...' which shows as double ::

This is what I propose provided we add that app name fallback in the label:

<img width="837" alt="image" src="https://github.com/Laragear/TwoFactor/assets/146040315/3ee3fcda-243e-4905-9a6f-eb26de0342e8">

```
        [$issuer, $account_name] = explode(':', $this->attributes['label'] ?? '');
        if (!$issuer) throw new InvalidArgumentException('The TOTP issuer cannot be empty.');
        if (!$account_name) throw new InvalidArgumentException('The TOTP account name cannot be empty.');
        $query = http_build_query([
            'issuer'    => $issuer,
            'label'     => $this->attributes['label'],
            'secret'    => $this->shared_secret,
            'algorithm' => strtoupper($this->attributes['algorithm']),
            'digits'     => $this->attributes['digits'],
        ], '', '&', PHP_QUERY_RFC3986);

        return 'otpauth://totp/'.rawurlencode($issuer).'%3A'.$account_name."?$query";
```

Hope this helps in keeping your library awesome.

This is the mitigation I've done in my project, in case someone needs it:
```
$user = Auth::user();
$secret = $user->createTwoFactorAuth();
$uri_params = explode('?', $secret->toUri())[1];
$uri = 'otpauth://totp/' . rawurlencode(config('two-factor.issuer')) . ':' . $user->email . '?' . $uri_params;
```

Regards and saludos,

**Comment by juanparati** [comment]
I can also experience that issues is duplicate due that label already has the issuer, however I also think that we should take care modifying the behavior because different authentication apps can represent the label and issuer in different ways.
