### ISSUE TITLE
La autenticación de dos factores no autentica.

### ISSUE THREAD

**Issue by marcovilella** [Laragear/TwoFactor#86]
### PHP & Platform

8.3.6 windows 64bits

### Database

Sql Server 2019

### Laravel version

10.48.22

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

Cuando ingreso el código de 6 dígitos y espero a que valide y otorgue acceso.

### Description

la función: "confirmTwoFactorAuth" devuelve falso en lugar de verdadero

### Reproduction

```php
$user =  $this->user->confirmTwoFactorAuth($this->code);
if ($user) {
    return home;
} else {
    return false;
}
```

**Comment by DarkGhostHunter** [comment]
The actual confirmation [happens in this code](https://github.com/Laragear/TwoFactor/blob/32b83989e930b17c9c14ed216d4ce55f3a523745/src/Models/Concerns/HandlesCodes.php#L53).

All tests pass, so check if:

- The code is not being reused, otherwise it will return `false`.
- Timezones are in sync (server and device).

You can also debug this by creating a 2FA code with `makeCode()` and compare it to what the user should input.
